server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todox?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: dev
    password: Momo520.
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

todox:
  storage-path: storage
